---
title: "Plotly and Flexdashboards"
author: "Melike Aksoy"
date: "2023-10-24"
output: github_document
---
```{r}
library(tidyverse)
library(plotly)

library(p8105.datasets)
```

Focus in NYC Airbnb data
```{r}
data("nyc_airbnb")

nyc_airbnb=
  nyc_airbnb |> 
  mutate(stars=review_scores_location/2) |> 
  select(borough= neighbourhood_group, neighbourhood, stars, price, room_type, lat, long) |> 
  drop_na(stars) |> 
  filter(
    borough=="Manhattan", 
    room_type=="Entire home/apt", 
    price %in% 100:500
  )
```


Let's make a scatterplot!
```{r}
nyc_airbnb |>
  mutate(text_label = str_c("Price: $", price, "\nRating: ", rating)) |> 
  plot_ly(
    x = ~lat, y = ~long, type = "scatter", mode = "markers",
    color = ~price, text = ~text_label, alpha = 0.5)
```

Let's make a box plot!

```{r}
nyc_airbnb |> 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) |> 
  plot_ly(y = ~price, color = ~neighbourhood, type = "box", colors = "viridis")
```


Let's make a bar plot!
```{r}
nyc_airbnb |> 
  count(neighbourhood) |> 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) |> 
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar", colors = "viridis")
```

#ggplotly

ggplot scatterplot

```{r}
ggp_scatter =
  nyc_airbnb |> 
  ggplot(aes(x= lat, y=long, color=price))+
  geom_point(alpha= .5)

ggplotly(ggp_scatter)
```


